plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  index.md

theme: jekyll-theme-cayman
title: Anti-racist action items for BISB
description: Compiled from various sources